### ISSUE TITLE
Add compatibility with Termux

### ISSUE THREAD

**Issue by T3stX** [markasoftware/anypaste#17]
Please, add compatibility with Android app [Termux](https://termux.com/).

I installed anypaste in the path `/data/data/com.termux/files/usr/local/bin` but when i try, for example, to list plugins i get an error about `/tmp/ap_get_info: No such file or directory`.

The problem concerns the path to `/tmp` which, in Termux, is specified in the variable `TMPDIR` and it is `/data/.data/com.termux/files/usr/tmp`.

**Comment by markasoftware** [comment]
I believe I've fixed all Termux-related problems on the `develop` branch (https://raw.githubusercontent.com/markasoftware/anypaste/develop/anypaste). I had `/tmp` hardcoded where `mktemp` calls should have been; I've corrected that.

It also seems like `file` isn't provided in the default Termux packages. Make sure to run `pkg install file` first!
