### ISSUE TITLE
Where do I find a full list of all the sites anypaste already supports via plugins?

### ISSUE THREAD

**Issue by github-userx** [markasoftware/anypaste#18]
Couldn’t find it on GitHub nor on the website.

**Comment by markasoftware** [comment]
Run `anypaste --list` to view plugins (requires Anypaste 1.1 or later).

**Comment by github-userx** [comment]
Thanks! Hehe I would have liked to see the list before I install the software! :D

**Comment by markasoftware** [comment]
Fat chance of that buddy, how am I supposed to get anyone to use Anypaste? :)
